name: Python Formatting Check

on:
  push:
    branches: [jazzy]
  pull_request:
    branches: [jazzy]

jobs:
  python_formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Black Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check --diff --line-length 90"
